# Generated by Django 5.0.7 on 2024-07-21 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredDevice',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=15)),
                ('mac_address', models.CharField(max_length=17)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('last_discovered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
