# Generated by Django 5.0.7 on 2024-07-21 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.discovereddevice')),
            ],
        ),
    ]
